src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=75, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(?string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use App\Repository\ContentRepository;

/**
 * @Route("/admin/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="admin_user_index", methods={"GET"})
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('admin/user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            //*****************file upload****************
            $file = $form['image']->getData(); //formdan gelen img get data olarak alıyor
            if ($file) { //eğer bu dosya varsa bu alana bir dosya select edilsiyse buraya gir
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension(); //bir tane rastgele dosya adı oluştur.4fffkjdf556f4fkfdldkf.jpeg gibi benzersiz bir isim olusturur
                //dosya adı bu olacak ve (.) uzantısını al birleştir
                try {
                    $file->move(  //dosyayı al move et
                        $this->getParameter('images_directory'), //image/direct kaydet demek. in servis.yaml dosyaında
                        $fileName
                    );
                } catch (FileException $e) {

                }
                $user->setImage($fileName);
            }

            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            //**************file upload***************
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('admin/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //*****************file upload****************
            $file = $form['image']->getData(); //formdan gelen img get data olarak alıyor
            if ($file) { //eğer bu dosya varsa bu alana bir dosya select edilsiyse buraya gir
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension(); //bir tane rastgele dosya adı oluştur.4fffkjdf556f4fkfdldkf.jpeg gibi benzersiz bir isim olusturur
                //dosya adı bu olacak ve (.) uzantısını al birleştir
                try {
                    $file->move(  //dosyayı al move et
                        $this->getParameter('images_directory'), //image/direct kaydet demek. in servis.yaml dosyaında
                        $fileName
                    );
                } catch (FileException $e) {

                }
                $user->setImage($fileName);
            }

            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            //**************file upload***************

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_user_index');
        }

        return $this->render('admin/user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_user_index');
    }

    private function generateUniqueFileName()
    {
        return md5(uniqid());
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Admin\Comment;
use App\Entity\User;
use App\Form\Admin\ChoiceType;
use App\Form\Admin\CommentType;
use App\Form\UserType;
use App\Repository\Admin\CommentRepository;
use App\Repository\SettingRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use App\Repository\ContentRepository;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index", methods={"GET"})
     */
    public function index(SettingRepository $settingRepository): Response
    {
        $setting = $settingRepository->findAll();
        return $this->render('user/show.html.twig', [
            'setting' => $setting,

        ]);
    }

    /**
     * @Route("/comments", name="user_comments", methods={"GET"})
     */
    public function comments(CommentRepository $commentRepository,SettingRepository $settingRepository): Response
    {
        $setting = $settingRepository->findAll();
        $user=$this->getUser();
        $comments=$commentRepository->getAllCommentsUser($user->getId());
        return $this->render('user/comments.html.twig',[
            'comments'=>$comments,
            'setting' => $setting,
        ]);
    }


    /**
     * @Route("/announcements", name="user_announcements", methods={"GET"})
     */
    public function announcements(): Response
    {
        return $this->render('user/announcements.html.twig');
    }

    /**
     * @Route("/news", name="user_news", methods={"GET"})
     */
    public function news(): Response
    {
        return $this->render('user/news.html.twig');
    }

    /**
     * @Route("/activities", name="user_activities", methods={"GET"})
     */
    public function activities(): Response
    {
        return $this->render('user/activities.html.twig');
    }


    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            //*****************file upload****************
            $file = $form['image']->getData(); //formdan gelen img get data olarak alıyor
            if ($file) { //eğer bu dosya varsa bu alana bir dosya select edilsiyse buraya gir
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension(); //bir tane rastgele dosya adı oluştur.4fffkjdf556f4fkfdldkf.jpeg gibi benzersiz bir isim olusturur
                //dosya adı bu olacak ve (.) uzantısını al birleştir
                try {
                    $file->move(  //dosyayı al move et
                        $this->getParameter('images_directory'), //image/direct kaydet demek. in servis.yaml dosyaında
                        $fileName
                    );
                } catch (FileException $e) {

                }
                $user->setImage($fileName);
            }

            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            //**************file upload***************
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_show", methods={"GET"})
     */
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, $id, User $user, UserPasswordEncoderInterface $passwordEncoder): Response
    {   //edit işleminde  id numarasının tarayıcıdan değiştrilerek başka kullanıcı bilgilerine erişilmesini engellemiş olduk.
        $user = $this->getUser(); //GET LOGİN USER DATA
        if ($user->getId() != $id) {
            return $this->redirectToRoute('home');
        }

        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //*****************file upload****************
            $file = $form['image']->getData(); //formdan gelen img get data olarak alıyor
            if ($file) { //eğer bu dosya varsa bu alana bir dosya select edilsiyse buraya gir
                $fileName = $this->generateUniqueFileName() . '.' . $file->guessExtension(); //bir tane rastgele dosya adı oluştur.4fffkjdf556f4fkfdldkf.jpeg gibi benzersiz bir isim olusturur
                //dosya adı bu olacak ve (.) uzantısını al birleştir
                try {
                    $file->move(  //dosyayı al move et
                        $this->getParameter('images_directory'), //image/direct kaydet demek. in servis.yaml dosyaında
                        $fileName
                    );
                } catch (FileException $e) {

                }
                $user->setImage($fileName);
            }

            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );
            //**************file upload***************

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_index');
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index');
    }

    private function generateUniqueFileName()
    {
        return md5(uniqid());
    }

    /**
     * @Route("/newcomment/{id}", name="user_new_comment", methods={"GET","POST"})
     */
    public function newcomment(Request $request,$id): Response
    {
        $comment = new Comment();
        $form = $this->createForm(UserType::class, $comment);
        $form->handleRequest($request);
        $submittedToken=$request->request->get('token'); //Submit token ile key tooken oluşturuyoruz

        if ($form->isSubmitted()) {
            if($this->isCsrfTokenValid('comment', $submittedToken)) {

                $entityManager = $this->getDoctrine()->getManager();
                $comment->setStatus('New');
                $comment->setIp($_SERVER['REMOTE_ADDR']);
                $comment->setContentid($id);
                $user=$this->getUser();
                $comment->setUserid($user->getId());

                $entityManager->persist($comment);
                $entityManager->flush();
                $this->addFlash('success', 'Your comment has been sent successfully');
                return $this->redirectToRoute('content_show', ['id' => $id]);
            }
        }
        return $this->redirectToRoute('content_show', ['id' => $id]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': app.user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ app.user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/activities.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}Profile{% endblock %}

{% block body %}
    <br><br><br><br><br><br><br><br><br><br>
    <!-- News -->
    <div class=" contact">
        <div class="col-lg-8">
            {{ include ('user/usermenu.html.twig') }}
            <div class="section_title_container text-lg-center">
                <div class="section_title">My Comment List</div>
            </div>

            <div class="row news_row">
                <div class="news_item">
                    <div class="news_content">
                        <div class="news_text">
                            <!-- News Post -->
My Announcements
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>
{% endblock %}

templates/user/announcements.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}Profile{% endblock %}

{% block body %}
    <br><br><br><br><br><br><br><br><br><br>
    <!-- News -->
    <div class=" contact">
        <div class="col-lg-8">
            {{ include ('user/usermenu.html.twig') }}
            <div class="section_title_container text-lg-center">
                <div class="section_title">My Comment List</div>
            </div>

            <div class="row news_row">
                <div class="news_item">
                    <div class="news_content">
                        <div class="news_text">
                            <!-- News Post -->
My Announcements
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>
{% endblock %}

templates/user/comments.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}Profile{% endblock %}

{% block body %}
    <script language="JavaScript" type="text/javascript">
        function openWin( windowURL, windowName, windowFeatures) { window.open( windowURL, windowName, windowFeatures);
        }
    </script>
    <br><br><br><br><br><br><br><br><br><br>
    <!-- News -->
    <div class=" contact">

        <div class="section_title_container text-lg-center">
            <div class="section_title">My Comment List</div> {{ include ('user/usermenu.html.twig') }}
        </div>
        {#        {{ include ('user/usermenu.html.twig') }}#}
        <div class="row news_row">
            <div class="news_item">
                <div class="news_content">
                    <div class="news_text">
                        <!-- News Post -->
                        <a href="{{ path('user_content_new') }}" class="btn btn-primary">Add new Content</a>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Subject</th>
                                <th>Comment</th>
                                <th>Status</th>
                                <th>Content</th>
                                <th>Created_at</th>
                                <th>Rate</th>
                                <th>actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for comment in comments %}
                                <tr>

                                    <td>{{ comment.subject }}</td>
                                    <td>{{ comment.comment }}</td>
                                    <td>{{ comment.status }}</td>

                                    <td><a href="{{ path('content_show',{'id': comment.id }) }}">{{ comment.title }}</a></td>
                                    <td>{{ comment.created_at }}</td>
                                    <td>{{ comment.rate }}</td>
                                    {#                                        <td>#}
                                    {#                                            <a href="{{ path('admin_comment_show', {'id': comment.id}) }}" class="btn btn-primary">show</a>#}
                                    {#                                        </td>#}
                                    {#                                        <td> <a href="{{ path('admin_comment_edit', {'id': comment.id}) }}" class="btn btn-success">edit</a></td>#}
                                    <td>
                                        {{ include('admin/comment/_delete_form.html.twig') }}
                                    </td>

                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="10">no records found</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>


                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>
{% endblock %}

templates/user/contents.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}Profile{% endblock %}

{% block body %}
    <br><br><br><br><br><br><br><br><br>
    <!-- News -->
    {#    <div class=" contact">#}
    {#        <div class="col-lg-8">#}
    {#            {{ include ('user/usermenu.html.twig') }}#}
    {#            <div class="section_title_container text-lg-center">#}
    {#                <div class="section_title">My Comment List</div>#}
    {#            </div>#}
    {{ include ('user/usermenu.html.twig') }}
    <div class="container">
        <div>
            <div class="col">
                <div class="section_title_container text-center">
                    <div class="section_subtitle"></div>
                    <div class="section_title">My Announcement</div>
                </div>
            </div>
        </div>
        <div class="row news_row">
            <div class="news_item">
                <div class="news_content">
                    <div class="news_text">
                        <!-- News Post -->
                        My Contents
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    <br><br>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User List{% endblock %}

{% block body %}

    <script language="JavaScript" type="text/javascript">
        function openWin( windowURL, windowName, windowFeatures) { window.open( windowURL, windowName, windowFeatures);
        }
    </script>
    <div class="dashboard-wrapper">
        <div class="container-fluid dashboard-content">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h1>Users List Table</h1>


                    <table class="table">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Email</th>
                            <th>Roles</th>
                            <th>Password</th>
                            <th>Name</th>
                            <th>Surname</th>
                            <th>Image</th>
                            <th>Status</th>
                            <th>Created_at</th>
                            <th>Updated_at</th>
                            <th>actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                                <td>{{ user.password }}</td>
                                <td>{{ user.name }}</td>
                                <td>{{ user.surname }}</td>
                                <td>{{ user.image }}</td>
                                <td>{{ user.status }}</td>
                                <td>{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                                <td>{{ user.updatedAt ? user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                                <td>
                                    <a href="{{ path('user_show', {'id': user.id}) }}" class="btn btn-primary btn-block">Show</a>
                                </td>
                                <td>
                                    <a href="{{ path('user_edit', {'id': user.id}) }}" class="btn btn-success">Edit</a>
                                </td>
                                <td>
                                    {{ include ('user/_delete_form.html.twig') }}
                                </td>

                            </tr>
                        {% else %}
                            <tr>
                                <td colspan="11">no records found
                                    <a href="{{ path('user_new') }}">Create new</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>


                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}
    <div class="col-md-2">
        <a href="{{ path('user_index') }}" class="btn-primary">back to list</a>
    </div>
{% endblock %}


{#{% extends 'base.html.twig' %}#}

{#{% block title %}New Content{% endblock %}#}

{#{% block body %}#}

{#    <!-- ============================================================== -->#}
{#    <!-- wrapper  -->#}
{#    <!-- ============================================================== -->#}
{#    <div class="dashboard-wrapper">#}
{#        <div class="container-fluid dashboard-content">#}
{#            <div class="row">#}
{#                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">#}

{#                    <h1>Create new User</h1>#}

{#                    {{ include('user/_form.html.twig') }}#}

{#                    <a href="{{ path('user_index') }}">back to list</a>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#{% endblock %}#}

templates/user/show.html.twig
{% extends 'homebase.html.twig' %}

{% block title %}{{ app.user.name }}Profile{% endblock %}

{% block body %}

    <br><br><br><br><br><br><br><br><br><br>
    <!-- News -->
    <div class=" contact">

        <div class="section_title_container text-lg-center">
            <div class="section_title">My User Profile</div>
            {{ include ('user/usermenu.html.twig') }}
        </div>
{#        {{ include ('user/usermenu.html.twig') }}#}
        <div class="row news_row">
            <div class="news_item">
                <div class="news_content">
                    <div class="news_text">
                        <!-- News Post -->
                        <table class="table">
                            <tbody>
                            <tr>
                                <th>Id</th>
                                <td>{{ app.user.id }}</td>
                            </tr>
                            <tr>
                                <th>Email</th>
                                <td>{{ app.user.email }}</td>
                            </tr>
                            <tr>
                                <th>Roles</th>
                                <td>{{ app.user.roles ? app.user.roles|json_encode : '' }}</td>
                            </tr>
                            <tr>
                                <th>Password</th>
                                <td>{{ app.user.password }}</td>
                            </tr>
                            <tr>
                                <th>Name</th>
                                <td>{{ app.user.name }}</td>
                            </tr>
                            <tr>
                                <th>Surname</th>
                                <td>{{ app.user.surname }}</td>
                            </tr>
                            <tr>
                                <th>Image</th>
                                <td>{{ app.user.image }}</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>{{ app.user.status }}</td>
                            </tr>
{#                            <tr>#}
{#                                <th>Created_at</th>#}
{#                                <td>{{ app.user.createdAt ? app.user.createdAt|date('Y-m-d H:i:s') : '' }}</td>#}
{#                            </tr>#}
{#                            <tr>#}
{#                                <th>Updated_at</th>#}
{#                                <td>{{ app.user.updatedAt ? app.user.updatedAt|date('Y-m-d H:i:s') : '' }}</td>#}
{#                            </tr>#}
                            </tbody>
                        </table>
                        <a href="{{ path('user_edit', {'id': app.user.id}) }}" class="btn btn-space btn-success">Edit Profile</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>
{% endblock %}